### ISSUE TITLE
Suggestion: error 500 auto message

### ISSUE THREAD

**Issue by SharkZekrom** [Azuriom/AzuriomBot#6]
Hello, i have a suggestion

if member post a message in channel support and the message contains "erreur 500" or other, the bot will reply with a auto message for logs :)

**Comment by MrMicky-FR** [comment]
This would be pretty spammy, as even if the user send the logs and also says he has an 500 error the bot would send the message. IMHO the `/logs` command is pretty fast and is a good workaround
